sudo: required

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  - sleep 4
  - atma &
  - atma server &
  - sleep 4
  - firefox http://localhost:5777/utest/ &
  - sleep 4
 
script:
  - "npm test"
 
language: node_js

node_js:
    - "10.1.0"
  