before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - atma &
  - atma server &
  - sleep 4
  - firefox http://localhost:5777/utest/ &
  - sleep 4
 
script:
  - "npm test"
 
language: node_js
node_js:
  - "8.0.0"
